# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: http-client-socks
version: '0.1.0'
github: "srhoulam/http-client-socks"
license: MIT
author: "Saad Rhoulam <saad@rhoulam.tech>"
maintainer: "Saad Rhoulam <saad@rhoulam.tech>"
synopsis: SOCKS proxy support in non-TLS HTTP.
description: |
  This package fills an HTTP client library gap: SOCKS without TLS.
  The starting point is borrowed internal code from http-client-tls.
category: Network

extra-source-files:
- LICENSE.md
- package.yaml
- stack.yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  dependencies:
  - base
  - connection >= 0.3.1 && < 0.4
  - http-client >= 0.6.4 && < 0.7
  source-dirs: src
